### ISSUE TITLE
[Migration Issue]: Home Page Carousel shows only One book when two present

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi-web-console#26]
In The Home Page, Only one book is shown. If we click on View All, then two books are shown.
Please find attached screenshot.

One More Issue: if Not Books Present, still an empty distorted carousel in Home page is shown. If No Books Present, Carousel should not be shown in Home Page

**Comment by damooo** [comment]
other one may not have thumbnail. previously too, if thumbnail not present, it will be filtered away instead of filler.. I thought that is design decission; and hence kept it like that. should i  fill with filler thumbnail anna?

**Comment by shashikiranraifox** [comment]
Yes. Default Image was shown earlier. Please show the same. Please also check for Mobile Responsiveness.  
Also please check, if there are no books, Empty carousel is shown. Carousel should not be shown if no books Present.
@damooo Will create a new branch for this fix and share with you. Right now merging into development.

**Comment by damooo** [comment]
sare anna.

**Comment by shashikiranraifox** [comment]
@damooo  Please use the Branch **home_carousel_issue** for pushing this fix changes.

**Comment by shashikiranraifox** [comment]
The Issue does not occur on the Latest Development Branch.
