### ISSUE TITLE
[Migration Issue]: Login from any other page other than home page  without setting server URL does not work

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi-web-console#30]
1. The Home Page has a Login Option in the Nav bar menu on top.
2. If we set the Server URL. and click on the login option, login form is displayed and we can log in to the application.
3. If we don't set the Login URL and then go to a different page[Let's say Book List] and click on Login. the Login Form does not pop-up

Probable Fix: Clicking on Login option. if the Server URL was not set in Home Page, then if login  option is clicked from a different page. We can display a different page to enter the server URL where registration[API call] can occur. After Registration is complete the Login Form should be popped up for the user to login. After login the User should be taken to the default page to be shown after login.

**Comment by damooo** [comment]
seems, working on https://apps.vedavaapi.org/stage/ui/book/5cbd5f469218e60008547067 . how can i reproduce it?

**Comment by shashikiranraifox** [comment]
I am talking about Fresh Login. Clicking on the Login Option. Does not display any Login Pop-up. In the same link you have shared. 
I shall share the video shortly.

**Comment by damooo** [comment]
got it anna. presently you kept site chosing modal in home page only. hence in fresh login, there is no site set, when we go to other page directly by url. hence, the problem it seems. better if we factor out site choosing model into separate component, and add it to every route.. so that when user come to a internal page for first time, not through home page, then also that model can be displayed.

**Comment by shashikiranraifox** [comment]
@damooo  As you have pointed out if the Site URL is not set. Then the issue occurs. I shall modify the description.

**Comment by sai-r-susarla** [comment]
Hi Shashi,
Can you take the responsibility of UI issues not directly connected with backend interactions?
Thanks,
- Sai.

**Comment by shashikiranraifox** [comment]
Sai,
    Migration to a new Login Scheme was done by @damooo . This scenario was probably missed during the testing phase.

Will revert on this thread.

Regards,
Shashi Kiran G M

**Comment by damooo** [comment]
Yes anna. but before too, when user not set the site_url and landed in some page, then there will be no functionality what ever it may, as site_url is not defined. we can have the model component in every route to be displayed, if site_url is not set.

**Comment by sai-r-susarla** [comment]
@shashikiranraifox, the expected functionality is that from whichever page on the web console application, there has to be a check right at the beginning whether site_url is set. If not, the user should be redirected to connect to a Vedavaapi site.

**Comment by shashikiranraifox** [comment]
Correct me if I am wrong. Vedavaapi site here refers to the Home page where Pop for Server URL is asked right?
I think this small re-direction can be done. Please confirm

**Comment by sai-r-susarla** [comment]
Yes. Vedavaapi site is the same URL that the user typed when asked for Server URL.
Rename it as "Vedavaapi Server URL".

**Comment by shashikiranraifox** [comment]
Noted. Will do the needful.

**Comment by shashikiranraifox** [comment]
Fixed the Issue. if Server URL is not present, then clicking on the Login Button, it re-directs to the Home page where the Pop up to enter server url is displayed.

**Comment by shashikiranraifox** [comment]
Fixed in Branch pagination_and_pending_issues
