### ISSUE TITLE
[Migration Issue]: Once a User Logs in, there is no way to choose a Different User account to login next time.

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi-web-console#31]
1. Login to the Vedavaapi Web console application.
2. Logout of the Application.
3. Click on Login again. 
4. We can only login with the same user account as credentials are stored to local storage.
Note: If we delete the local storage then only I can get the login form to enter username and password. 

Expected Result: There should be an option to enter a different user account details to login without having to use the hack of deleting local storage details.

**Comment by damooo** [comment]
yes. presently it only 'unauthorizes' the client. not logout from primary api. we can add logout api call also.

**Comment by sai-r-susarla** [comment]
Logout means logout of everything. Remove all client and user state.

**Comment by shashikiranraifox** [comment]
Closed by @damooo  as part of API migration. Verified after merge with dev branch.
