### ISSUE TITLE
Vedavaapi site connection management from web console

### ISSUE THREAD

**Issue by sai-r-susarla** [vedavaapi/vedavaapi-web-console#34]
The web console should show somewhere the Vedavaapi site to which it is currently connected.
There should be a way to change it or remove the connection.
When removed, it should go back to ask the user to supply a new site url.

**Comment by shashikiranraifox** [comment]
The Enhancement has been implemented. Just the merge to development is pending. @gdkirankumar  will do the needful and raise a pull request.

**Comment by shashikiranraifox** [comment]
Feature Implemented and merged with Development Branch.
