### ISSUE TITLE
[Migration Issue][Blocker] Unable to add/remove members and perform other operations on a Team

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi-web-console#38]
This functionality was present in the development  branch but seems to be unavailable in the Pull request #37 

1. Login as Root Admin[info@vedavaapi.org]
2. Create a  few Teams.
3. The Only operation I can perform on the  any Team is to Just View the Team.

I was able to add/remove members from the team, update Team permissions on the account of me being a Root Admin or atleast the admin of the team.

**Comment by shashikiranraifox** [comment]
@damooo  Probably because the response format has changed, we provide the various actions that can be performed on team by checking permissions.

**Comment by damooo** [comment]
yes . now api provides resolvedPermissions, with already resolved booleans.. it is mentioned in one issue. i am updating and pushing now.

**Comment by shashikiranraifox** [comment]
Ok you may have to modify certain methods in paged-data-component.ts . Check the method
checkIfPermissionPresent
isMemberOfTeam

Please test it completely before raising a pull request.

**Comment by damooo** [comment]
now it is pushed. and on /dev/ui.
as i mentioned it in other issue, i thought any design decissions are to made for resolvedPermissions, and hence didn't touch it anna. now it is working. checkIfPermissionPresent is now not needed, as boolean is already available in resource's definition.

**Comment by damooo** [comment]
for adding/removing members in a group permission to be checked is 'updateContent' over that group anna. updateLinks are for modifying `source`/`target` link only. I didn't changed that one at https://github.com/vedavaapi/vedavaapi-web-console/blob/c2144221ab24394cbefb29324d7ecbaa05b14457/src/app/ui/group-list/group-list.component.html#L41
as it may require your review.

**Comment by shashikiranraifox** [comment]
@damooo  i am unable to grant permissions to any member of the team. Please use updatePermisisons action to test the same . The error thrown is resource does not exist.

**Comment by damooo** [comment]
fixed anna. a `/` missed in url.

**Comment by shashikiranraifox** [comment]
Verified. Working after the merge from api_migration branch.
