### ISSUE TITLE
Login popup Styling not as per Theme

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi-web-console#47]
The Pop up displayed for Login and Authorization is not as per theme.
The Pages are actually served from the Server Side itself. Henceforth we have created the HTML Pages. Sharing the same with @damooo so the shared pages which has adequate styling can be used in place of the current pages.

**Comment by damooo** [comment]
where are they anna...

**Comment by shashikiranraifox** [comment]
@damooo I have shared the New Pages over email.

**Comment by damooo** [comment]
Yes , got them. Thanks anna.

**Comment by damooo** [comment]
merged with commit https://github.com/vedavaapi/core_services/commit/72fe7b63bc2b98031bc16ec30ff97bdc3eb39e10
live on prod server
