### ISSUE TITLE
Supporting Libraries

### ISSUE THREAD

**Issue by damooo** [vedavaapi/vedavaapi-web-console#7]
Now we have api support for libraries. analogous to book collections.
i.e each book will be member of a collection. at the time of creating new one, we post it to a library, setting it's 'source' field to library _id.
 so to create new libraries, and to list existing libraries, etc, ui have to be created. and at the time of creating book, we should be able to choose to which library we have to add it.
And at the time of mirador visualization, we should be able to visualize selected library(analogous to mirador collections), as in #6 .

**Comment by shashikiranraifox** [comment]
Support for Libraries Added.
